### ISSUE TITLE
can not ng serve the app

### ISSUE THREAD

**Issue by kimmiekim** [codeschool/WatchUsBuild-Angular2Final#2]
Hi I git cloned the repo and installed angular-cli in my command line, but every time I run ng serve, 
I get 

/usr/local/lib/node_modules/ng-cli/node_modules/resolve/lib/sync.js:36
    throw new Error("Cannot find module '" + x + "' from '" + y + "'");
    ^

Error: Cannot find module 'ng-factory' from '/Users/kimmiekim/Desktop/Folders/personal/WatchUsBuild-Angular2Final'
    at Function.module.exports [as sync] (/usr/local/lib/node_modules/ng-cli/node_modules/resolve/lib/sync.js:36:11)
    at module.exports (/usr/local/lib/node_modules/ng-cli/node_modules/resolve-require/lib/index.js:10:24)
    at Command.<anonymous> (/usr/local/lib/node_modules/ng-cli/lib/index.js:49:5)
    at Command.listener (/usr/local/lib/node_modules/ng-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/ng-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/ng-cli/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/ng-cli/lib/index.js:55:9)
    at Module._compile (module.js:541:32)

Thanks!

**Comment by arakno76** [comment]
@kimmiekim have you tried to "npm install" first?
